### ISSUE TITLE
Provide link to history of Typelevel's abuse, or remove this from the repo

### ISSUE THREAD

**Issue by axb21** [fwbrasil/kyo#2]
There is a claim in this repo's README that Typelevel has a "history of online attacks targeting...members of minority groups". Please provide evidence supporting this claim, or remove it. It is libelous without evidence, besides being annoying and not useful in an open source project. You don't even give a positive code of conduct, you just pick on someone else's.

cc @djspiewak @alexandru

**Comment by fwbrasil** [comment]
I do have something I prepared months ago but I believe it would just make matters worse. Typelevel’s history is well known within the community and the goal of the policy is to keep them away from the project.

That said, I’d be open to sharing what I have if the Typelevel leadership requests it. Feel free to reopen this issue if that’s the case.

**Comment by axb21** [comment]
Typelevel's history is *not* well-known. You are making that up. Provide evidence, or remove the statement. Libel is a crime in the United States and I will continue to report this repository to github until you rectify this somehow.
